title: "Journées Francophones<br>de Programmation par Contraintes<br>et d’Intelligence Artificielle Fondamentale"
shorttitle: "JFPC et JIAF"
date: "JFPC et JIAF<br>Du 2 au 5 juin 2020"
location: "Nice"
description: > # this means to ignore newlines until "baseurl:"
    "JFPC 2020 et JIAF 2020 du 2 au 5 juin à Nice"
baseurl: "jfpc_jiaf_2020" # the subpath of your site, e.g. /blog
url: "http://i3s.unice.fr"

sidebar:
  - title: "Soumission du résumé"
    text: "TBA"
  - title: "Soumission de l'article"
    text: "TBA"

facebook:
  app_id: 

logo: "⁨assets⁩/img/favicon.png"

language: 'fr'

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github fa-lg
    url: https://github.com/mpelleau/jfpc2020
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: :expanded
  line_numbers: true
  sourcemap: always

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
